// source: root.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Annotation');
goog.provide('proto.Annotation.RelevantEntityCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Expression');
goog.require('proto.Token');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Annotation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.Annotation.oneofGroups_);
};
goog.inherits(proto.Annotation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Annotation.displayName = 'proto.Annotation';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.Annotation.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.Annotation.RelevantEntityCase = {
  RELEVANT_ENTITY_NOT_SET: 0,
  ENTITY: 2,
  TOKEN: 3,
  EXPRESSION: 4
};

/**
 * @return {proto.Annotation.RelevantEntityCase}
 */
proto.Annotation.prototype.getRelevantEntityCase = function() {
  return /** @type {proto.Annotation.RelevantEntityCase} */(jspb.Message.computeOneofCase(this, proto.Annotation.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Annotation.prototype.toObject = function(opt_includeInstance) {
  return proto.Annotation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Annotation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Annotation.toObject = function(includeInstance, msg) {
  var f, obj = {
    note: jspb.Message.getFieldWithDefault(msg, 1, ""),
    entity: jspb.Message.getFieldWithDefault(msg, 2, ""),
    token: (f = msg.getToken()) && proto.Token.toObject(includeInstance, f),
    expression: (f = msg.getExpression()) && proto.Expression.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Annotation}
 */
proto.Annotation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Annotation;
  return proto.Annotation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Annotation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Annotation}
 */
proto.Annotation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNote(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEntity(value);
      break;
    case 3:
      var value = new proto.Token;
      reader.readMessage(value,proto.Token.deserializeBinaryFromReader);
      msg.setToken(value);
      break;
    case 4:
      var value = new proto.Expression;
      reader.readMessage(value,proto.Expression.deserializeBinaryFromReader);
      msg.setExpression(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Annotation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Annotation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Annotation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Annotation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNote();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getToken();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.Token.serializeBinaryToWriter
    );
  }
  f = message.getExpression();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.Expression.serializeBinaryToWriter
    );
  }
};


/**
 * optional string note = 1;
 * @return {string}
 */
proto.Annotation.prototype.getNote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Annotation} returns this
 */
proto.Annotation.prototype.setNote = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string entity = 2;
 * @return {string}
 */
proto.Annotation.prototype.getEntity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Annotation} returns this
 */
proto.Annotation.prototype.setEntity = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.Annotation.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Annotation} returns this
 */
proto.Annotation.prototype.clearEntity = function() {
  return jspb.Message.setOneofField(this, 2, proto.Annotation.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Annotation.prototype.hasEntity = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Token token = 3;
 * @return {?proto.Token}
 */
proto.Annotation.prototype.getToken = function() {
  return /** @type{?proto.Token} */ (
    jspb.Message.getWrapperField(this, proto.Token, 3));
};


/**
 * @param {?proto.Token|undefined} value
 * @return {!proto.Annotation} returns this
*/
proto.Annotation.prototype.setToken = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.Annotation.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Annotation} returns this
 */
proto.Annotation.prototype.clearToken = function() {
  return this.setToken(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Annotation.prototype.hasToken = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Expression expression = 4;
 * @return {?proto.Expression}
 */
proto.Annotation.prototype.getExpression = function() {
  return /** @type{?proto.Expression} */ (
    jspb.Message.getWrapperField(this, proto.Expression, 4));
};


/**
 * @param {?proto.Expression|undefined} value
 * @return {!proto.Annotation} returns this
*/
proto.Annotation.prototype.setExpression = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.Annotation.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Annotation} returns this
 */
proto.Annotation.prototype.clearExpression = function() {
  return this.setExpression(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Annotation.prototype.hasExpression = function() {
  return jspb.Message.getField(this, 4) != null;
};


