// source: root.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Expression');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Token');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Expression = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Expression.repeatedFields_, null);
};
goog.inherits(proto.Expression, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Expression.displayName = 'proto.Expression';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Expression.repeatedFields_ = [6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Expression.prototype.toObject = function(opt_includeInstance) {
  return proto.Expression.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Expression} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Expression.toObject = function(includeInstance, msg) {
  var f, obj = {
    raw: jspb.Message.getFieldWithDefault(msg, 5, ""),
    tokensList: jspb.Message.toObjectList(msg.getTokensList(),
    proto.Token.toObject, includeInstance),
    expressionsList: jspb.Message.toObjectList(msg.getExpressionsList(),
    proto.Expression.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Expression}
 */
proto.Expression.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Expression;
  return proto.Expression.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Expression} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Expression}
 */
proto.Expression.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRaw(value);
      break;
    case 6:
      var value = new proto.Token;
      reader.readMessage(value,proto.Token.deserializeBinaryFromReader);
      msg.addTokens(value);
      break;
    case 7:
      var value = new proto.Expression;
      reader.readMessage(value,proto.Expression.deserializeBinaryFromReader);
      msg.addExpressions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Expression.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Expression.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Expression} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Expression.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRaw();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTokensList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.Token.serializeBinaryToWriter
    );
  }
  f = message.getExpressionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.Expression.serializeBinaryToWriter
    );
  }
};


/**
 * optional string raw = 5;
 * @return {string}
 */
proto.Expression.prototype.getRaw = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Expression} returns this
 */
proto.Expression.prototype.setRaw = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated Token tokens = 6;
 * @return {!Array<!proto.Token>}
 */
proto.Expression.prototype.getTokensList = function() {
  return /** @type{!Array<!proto.Token>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Token, 6));
};


/**
 * @param {!Array<!proto.Token>} value
 * @return {!proto.Expression} returns this
*/
proto.Expression.prototype.setTokensList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.Token=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Token}
 */
proto.Expression.prototype.addTokens = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.Token, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Expression} returns this
 */
proto.Expression.prototype.clearTokensList = function() {
  return this.setTokensList([]);
};


/**
 * repeated Expression expressions = 7;
 * @return {!Array<!proto.Expression>}
 */
proto.Expression.prototype.getExpressionsList = function() {
  return /** @type{!Array<!proto.Expression>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Expression, 7));
};


/**
 * @param {!Array<!proto.Expression>} value
 * @return {!proto.Expression} returns this
*/
proto.Expression.prototype.setExpressionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.Expression=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Expression}
 */
proto.Expression.prototype.addExpressions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.Expression, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Expression} returns this
 */
proto.Expression.prototype.clearExpressionsList = function() {
  return this.setExpressionsList([]);
};


