[package]
name = "extraction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.25.2"
walkdir = "2"
lazy_static = "1.4.0"
regex = "1"