[package]
name = "runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extraction = { path = "../extraction"}
protobuf = "2.25.2"
base64 = "0.13.0"